### PR TITLE
fix: changed colors and fixed minor issues

### LINKED ISSUE #183: BUG: Renew and Pending Tables not showing the right data

### LINKED ISSUE #184: BUG: pending leases shouldn’t show the renew button in the dashboard

### PR DESCRIPTION
**Pull request by 227Faddi**
Solved some bugs and changed the main colors of the app to make everything more consistent.

[#184](https://github.com/brianangulo/feb-2025-DSD-cohort/issues/184)
[#183](https://github.com/brianangulo/feb-2025-DSD-cohort/issues/183)

### CODE REVIEW

File: front-end/src/components/aptdetails/Notes.jsx [hunk 1]
```diff
@@ -46,10 +45,10 @@ const Notes = ({ apartmentData }) => {
...
-      <Card sx={{ height: 350, textAlign: "center" }}>
+      <Card sx={{ height: 350, textAlign: "center", border: 0.5 }}>
         <Typography
-          className=" text-white text-center py-3 text-lg font-semibold rounded-t-lg"
-          bgcolor={"#206129"}
+          className="text-center py-3 text-lg font-semibold"
+          bgcolor={"#e3e7d3"}
         >
           Notes
         </Typography>
```
Comment (johnmdrake1) [inline front-end/src/components/aptdetails/Notes.jsx:54]: Make sure the margin top I added on line 56/57 for the button gets fixed if you have to solve a conflict regarding it.

File: front-end/src/components/aptdetails/Features.jsx [hunk 2]
```diff
@@ -51,10 +50,10 @@ const Features = ({ apartmentData }) => {
...
-      <Card sx={{ height: 350, textAlign: "center" }}>
+      <Card sx={{ height: 350, textAlign: "center", border: 0.5 }}>
         <Typography
-          className=" text-white text-center py-3 text-lg font-semibold rounded-t-lg"
-          bgcolor={"#206129"}
+          className="text-center py-3 text-lg font-semibold"
+          bgcolor={"#e3e7d3"}
         >
           Features
         </Typography>
```
Comment (johnmdrake1) [inline front-end/src/components/aptdetails/Features.jsx:59]: Same thing here, make sure the mt on the Add/remove features button added stays if a conflict arises near line 61

**Review by johnmdrake1 — APPROVED** [review]

**Comment by brianangulo** [comment]
[23:17:31.611] Cloning github.com/brianangulo/feb-2025-DSD-cohort (Branch: fix/styles-and-minor-bugs, Commit: 8aa9e37)
[23:17:32.038] Cloning completed: 427.000ms
[23:17:32.774] Restored build cache from previous deployment (5398K39hh8K2EpxSfz5BzBnnehKD)
[23:17:32.864] Running build in Washington, D.C., USA (East) – iad1
[23:17:33.982] Running "vercel build"
[23:17:34.556] Vercel CLI 41.4.1
[23:17:35.226] Installing dependencies...
[23:17:36.602] 
[23:17:36.603] up to date in 1s
[23:17:36.604] 
[23:17:36.604] 137 packages are looking for funding
[23:17:36.604]   run `npm fund` for details
[23:17:37.383] [36mvite v6.2.2 [32mbuilding for production...[36m[39m
[23:17:37.459] transforming...
[23:17:37.922] [32m✓[39m 41 modules transformed.
[23:17:37.924] [31m✗[39m Build failed in 503ms
[23:17:37.924] [31merror during build:
[23:17:37.924] [31m[vite:esbuild] Transform failed with 1 error:
[23:17:37.925] /vercel/path0/front-end/src/pages/AccountSettings.jsx:125:0: ERROR: Unexpected end of file before a closing "Box" tag[31m
[23:17:37.925] file: [36m/vercel/path0/front-end/src/pages/AccountSettings.jsx:125:0[31m
[23:17:37.925] [33m
[23:17:37.925] [33mUnexpected end of file before a closing "Box" tag[33m
[23:17:37.925] 123|  
[23:17:37.925] 124|  export default AccountSettings;
[23:17:37.925] 125|  
[23:17:37.925]    |  ^
[23:17:37.925] [31m
[23:17:37.925]     at failureErrorWithLog (/vercel/path0/front-end/node_modules/esbuild/lib/main.js:1477:15)
[23:17:37.925]     at /vercel/path0/front-end/node_modules/esbuild/lib/main.js:756:50
[23:17:37.925]     at responseCallbacks.<computed> (/vercel/path0/front-end/node_modules/esbuild/lib/main.js:623:9)
[23:17:37.926]     at handleIncomingPacket (/vercel/path0/front-end/node_modules/esbuild/lib/main.js:678:12)
[23:17:37.926]     at Socket.readFromStdout (/vercel/path0/front-end/node_modules/esbuild/lib/main.js:601:7)
[23:17:37.926]     at Socket.emit (node:events:518:28)
[23:17:37.926]     at addChunk (node:internal/streams/readable:561:12)
[23:17:37.926]     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
[23:17:37.926]     at Readable.push (node:internal/streams/readable:392:5)
[23:17:37.926]     at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)[39m
[23:17:37.945] Error: Command "NODE_ENV=production vite build" exited with 1
[23:17:38.432]

**Review by mhchen — APPROVED** [review]
